Implement `letter.lowercase` and `letter.uppercase`
danielroe/magic-regexp pull request #77
Opened 2022-10-26 01:49 UTC by ccjmne

Pretty trivial implementation!

However, something is wonky in the changes to the typings tests I introduced in c2200a478fbceb25fcd88f274e064ab7068c9acb...
The tests were broken by introducing `lowercase` and `uppercase` properties to `letter`, and when I tried reproducing a minimal example of it on typescriptlang.org, of course there, an `Asdf<T> & { yes: 'no' }` **does** extend `Asdf<any>`. I couldn't put my finger on what the fix should be.

There might be a better way to handle them through savvy typing of the `extractRegExp` function, but I couldn't figure it out myself. 🙇‍♀️

Resolves #37.

2022-10-26 14:20 UTC, danielroe requested changes
The test issues you encountered are flagging that the type generation is broken at the moment.

(To be clear, this is the most difficult part of the PR for the reason you've encountered.)

We might consider rethinking the API. Maybe `letter.any`, `letter.lowercase`, `letter.uppercase` as three in parallel? wdyt @didavid61202

2022-10-27 14:44 UTC, didavid61202 commented
HI @danielroe, @ccjmne . I've made a PR #79 related to the type inferencing issue encounter in the PR. 
If #70 is merged, we can remove the type casting in test file and merge this PR 👍

2022-10-27 15:04 UTC, danielroe commented on test/inputs.test.ts
> +  type Input,
```suggestion
  charNotIn,
```

2022-10-27 15:04 UTC, danielroe commented on test/inputs.test.ts
> +    expectTypeOf(extractRegExp(not.letter.uppercase)).toEqualTypeOf<'[^A-Z]'>()
```suggestion
    expectTypeOf(extractRegExp(not.letter)).toEqualTypeOf<'[^a-zA-Z]'>()
    expect(not.letter.lowercase.toString()).toMatchInlineSnapshot('"[^a-z]"')
    expectTypeOf(extractRegExp(not.letter.lowercase)).toEqualTypeOf<'[^a-z]'>()
    expect(not.letter.uppercase.toString()).toMatchInlineSnapshot('"[^A-Z]"')
    expectTypeOf(extractRegExp(not.letter.uppercase)).toEqualTypeOf<'[^A-Z]'>()
```

2022-10-27 15:22 UTC, danielroe approved these changes
Thank you both! ❤️

2022-10-27 15:22 UTC, merged

2022-10-27 15:30 UTC, ccjmne commented
This was really nice!
I should get off my butt and try to participate more in some open-source projects outside of Oktoberfest as well. 🤯

I learned some things, thought about some implementation details, read code that's not mine, discovered the Vite bundler, realised that pnpm is really getting popular...
All of that, by doing nearly nothing! 😂

Great experience 👍
Also, delightful interactions with you guys 😊

Cheers!

2022-10-27 15:51 UTC, didavid61202 commented
@ccjmne Thanks!
I'm also on the same track, trying to participate more in open-source projects, and have learned quite a lot from the best developers/maintainers like Daniel, Anthony, and Pooya Parsa (All from Nuxt team!). 
And I will highly recommend checking out [Nuxt repo](https://github.com/nuxt/framework) and [unjs repos](https://github.com/unjs) if you haven't 👍 

Thanks for your contribution! 💚 

Cheers! 🍻